logging:
  level:
    ROOT: INFO
spring:
  profiles:
    active: dev
  banner:
    image:
      location: banner.txt
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans

language-tag: en-US

